linters:
  enable-all: true
  disable:
    - depguard # use gomodguard
    # not useful
    - err113
    - lll
    - varnamelen
    # deprecated
    - gochecknoglobals
    - gomnd
    - execinquery

linters-settings:
  nlreturn:
    block-size: 3

issues:
  exclude:
    - "var-naming: don't use underscores in Go names;"
    - "ST1003: should not use underscores in Go names;"
