version: "2"
linters:
  default: all
  disable:
    - canonicalheader
    - depguard
    - err113
    - gochecknoglobals
    - lll
    - tagliatelle
    - varnamelen
    - noinlineerr
  settings:
    nlreturn:
      block-size: 3
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - funlen
          - gocritic
        path: _test\.go
      - path: (.+)\.go$
        text: fmt.Errorf can be replaced with errors.New
      - path: (.+)\.go$
        text: 'var-naming: don''t use underscores in Go names;'
      - path: (.+)\.go$
        text: 'ST1003: should not use underscores in Go names;'
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
