version: "2"
linters:
  default: all
  disable:
    - canonicalheader
    - depguard
    - err113
    - exhaustruct # deprecated
    - gochecknoglobals
    - gochecknoinits
    - godox
    - gomoddirectives
    - gomodguard
    - gosmopolitan
    - noinlineerr
    - lll
    - tagliatelle
    - varnamelen
    - wsl
  settings:
    exhaustruct_v5:
      enforce-patterns:
        - 'github.com/taomics/.*'
    nlreturn:
      block-size: 3
  exclusions:
    generated: lax
    warn-unused: true
    rules:
      - path: _test\.go
        linters:
          - exhaustruct_v5
          - funlen
          - revive
          - goconst
          - gocritic
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: strict
