name: auth

on:
  pull_request:
    paths:
      - 'auth/**'

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    env:
      GOEXPERIMENT: jsonv2

    steps:
    - name: Checkout code
      uses: actions/checkout@v7

    - name: Set up Go
      uses: actions/setup-go@v7
      with:
        go-version: '1.26'
        cache: true

    - name: Install dependencies
      working-directory: ./auth
      run: go mod download

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v9
      with:
        version: latest
        working-directory: ./auth

    - name: Run tests
      working-directory: ./auth
      run: go test -v ./...

    - name: Run govulncheck
      uses: golang/govulncheck-action@v1
      with:
        work-dir: ./auth
