name: pubsub

on:
  pull_request:
    paths:
      - 'pubsub/**'

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Install dependencies
      working-directory: ./pubsub
      run: go mod download

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v8
      with:
        version: latest
        working-directory: ./pubsub

    - name: Run tests
      working-directory: ./pubsub
      run: go test -v ./...

